v = input('digite algo: ')
print('o tipo primitivo é ', type)
print('possue apenas espaços? ', v.isspace())
print('é um número? ', v.isnumeric())
print('possue apenas letras?', v.isalpha())
print('possue letras e numeros?', v.isalnum())